"""
watsonx.ai REST API wrapper.

generate_explanation(asset_data) -> str

If WATSONX_API_KEY is not set (or is a placeholder), a deterministic
template string is returned so the demo works without a live API key.
If WATSONX_API_KEY is set, the function calls the watsonx.ai text
generation endpoint using ibm/granite-13b-chat-v2.
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict

import httpx
from dotenv import load_dotenv

load_dotenv()

_API_KEY: str = os.getenv("WATSONX_API_KEY", "")
_PROJECT_ID: str = os.getenv("WATSONX_PROJECT_ID", "")
_WATSONX_URL: str = os.getenv("WATSONX_URL", "https://us-south.ml.cloud.ibm.com")

_PLACEHOLDER_VALUES = {"", "your_watsonx_api_key_here", "placeholder"}


def _is_real_key() -> bool:
    return bool(_API_KEY) and _API_KEY.lower() not in _PLACEHOLDER_VALUES


def _template_explanation(asset_data: Dict[str, Any]) -> str:
    """Return a deterministic plain-language explanation from asset_data."""
    asset_id = asset_data.get("asset_id", "UNKNOWN")
    platform = asset_data.get("platform", "Unknown platform")
    status = asset_data.get("overall_status", "UNKNOWN")
    components = asset_data.get("components", [])

    red_comps = [c for c in components if c.get("status") == "RED"]
    amber_comps = [c for c in components if c.get("status") == "AMBER"]

    lines: list[str] = [
        f"READINESS ASSESSMENT — {asset_id} ({platform})",
        f"Overall Status: {status}",
        "",
    ]

    if red_comps:
        lines.append("CRITICAL DEFICIENCIES:")
        for c in red_comps:
            lines.append(
                f"  • {c['component'].upper()} — {c['metric']} = {c['value']} "
                f"(score {c['score']}/100). Immediate maintenance action required."
            )

    if amber_comps:
        lines.append("AMBER WARNINGS:")
        for c in amber_comps:
            lines.append(
                f"  • {c['component'].upper()} — {c['metric']} = {c['value']} "
                f"(score {c['score']}/100). Monitor closely; schedule service before next sortie."
            )

    if not red_comps and not amber_comps:
        lines.append("All monitored components are within acceptable operating parameters.")

    lines.append("")
    lines.append(
        "Assessment generated by Mission Readiness Officer rules engine "
        "(template mode — watsonx.ai key not configured)."
    )
    return "\n".join(lines)


def _get_iam_token() -> str:
    """Exchange the API key for a short-lived IAM bearer token."""
    resp = httpx.post(
        "https://iam.cloud.ibm.com/identity/token",
        data={
            "grant_type": "urn:ibm:params:oauth:grant-type:apikey",
            "apikey": _API_KEY,
        },
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()["access_token"]


def _call_watsonx(asset_data: Dict[str, Any]) -> str:
    """Call watsonx.ai and return the generated text."""
    token = _get_iam_token()

    prompt = (
        "You are a military aircraft maintenance analyst. "
        "Based on the following sensor readiness data, write a concise assessment "
        "(3–5 sentences) in military technical language. "
        "Identify which components are failing, state the risk level, "
        "and recommend the next maintenance action. "
        "Do not speculate beyond the data provided.\n\n"
        f"Asset Data:\n{json.dumps(asset_data, indent=2, default=str)}\n\n"
        "Assessment:"
    )

    payload = {
        "model_id": "ibm/granite-13b-chat-v2",
        "input": prompt,
        "parameters": {
            "decoding_method": "greedy",
            "max_new_tokens": 400,
            "stop_sequences": ["\n\n"],
        },
        "project_id": _PROJECT_ID,
    }

    url = f"{_WATSONX_URL}/ml/v1/text/generation?version=2023-05-29"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    resp = httpx.post(url, json=payload, headers=headers, timeout=60)
    resp.raise_for_status()
    results = resp.json().get("results", [])
    if results:
        return results[0].get("generated_text", "").strip()
    return _template_explanation(asset_data)


def generate_explanation(asset_data: Dict[str, Any]) -> str:
    """
    Generate a natural-language readiness explanation for an asset.

    Falls back to a template string if:
      - WATSONX_API_KEY is not set or is a placeholder
      - The API call fails for any reason
    """
    if not _is_real_key():
        return _template_explanation(asset_data)

    try:
        return _call_watsonx(asset_data)
    except Exception as exc:  # noqa: BLE001
        # Never let the LLM call crash the endpoint
        return _template_explanation(asset_data) + f"\n\n[watsonx.ai call failed: {exc}]"
